services:
  sonarqube:
    image: sonarqube:$SONARQUBE_VERSION
    container_name: sonarqube
    hostname: sonarqube
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: $POSTGRES_SONARQUBE_PASSWORD
    volumes:
      - sonarqube-config:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    image: postgres:$POSTGRES_SONARQUBE_VERSION
    container_name: postgres-sonarqube
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: $POSTGRES_SONARQUBE_PASSWORD
    volumes:
      - postgres-config:/var/lib/postgresql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  sonarqube-config:
  sonarqube-extensions:
  postgres-config:
  postgres-data:

networks:
  dev:
    external: true
