services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    hostname: open-webui
    restart: unless-stopped
    volumes:
      - data:/app/backend/data
    ports:
      - "8080:8080"
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  data:
