services:
  portainer:
    image: portainer/portainer-ce:$PORTAINER_VERSION
    container_name: portainer
    hostname: portainer
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - config:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  config:
