services:
  filebrowser:
    image: filebrowser/filebrowser:$FILE_BROWSER_VERSION
    container_name: filebrowser
    hostname: filebrowser
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    user: $USER_PUID:$USER_PGID
    volumes:
      - config/database.db:/database.db
      - $SHARED_FOLDER:/srv
    ports:
      - "80:80"
    security_opt:
      - no-new-privileges:true

volumes:
  config:
