services:
  jdownloader2:
    image: jlesage/jdownloader-2:$JDOWNLOADER2_VERSION
    container_name: jdownloader2
    hostname: jdownloader2
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    volumes:
      - config:/config
      - $SHARED_FOLDER/Downloads/HTTP:/output
    ports:
      - 5800:5800
      - 5900:5900
      - 3129:3129

volumes:
  config:
