services:
  jupyter-notebook:
    image: andresvidal/jupyter-armv7l:latest
    container_name: jupyter-notebook
    hostname: jupyter-notebook
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    command: --NotebookApp.token='$JUPYTER_NOTEBOOK_PASSWORD'
    volumes:
      - $SHARED_FOLDER/Notebooks:/notebooks
    ports:
      - "8888:8888"
