services:
  scrutiny:
    image: analogj/scrutiny:$SCRUTINY_VERSION
    container_name: scrutiny
    hostname: scrutiny
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    volumes:
      - config:/opt/scrutiny/config
      - influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda:/dev/sda

volumes:
  config:
  influxdb:
