services:
  code-server:
    image: linuxserver/code-server:$CODE_SERVER_VERSION
    container_name: code-server
    hostname: code-server
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
      - PROXY_DOMAIN=code-server.$DOMAIN_NAME
      - PASSWORD=$CODE_SERVER_PASSWORD
      - SUDO_PASSWORD=$CODE_SERVER_SUDO_PASSWORD
    volumes:
      - config:/config
      - $SHARED_FOLDER/Code:/code
    ports:
      - "8443:8443"
    networks:
      - code-server

volumes:
  config:

networks:
  code-server:
