services:
  jenkins:
    image: jenkins/jenkins:$JENKINS_VERSION
    container_name: jenkins
    hostname: jenkins
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    volumes:
      - config:/var/jenkins_home
    ports:
      - "8080:8080"
      - "5000:5000"
    networks:
      - dev

volumes:
  config:

networks:
  dev:
    external: true
