services:
  # plex:
  #   image: linuxserver/plex:$PLEX_VERSION
  #   container_name: plex
  #   hostname: plex
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #     - VERSION=docker
  #     - PLEX_CLAIM=$PLEX_CLAIM_TOKEN
  #   volumes:
  #     - plex-config:/config
  #     - $SHARED_FOLDER/Media:/media

  # tautulli:
  #   image: linuxserver/tautulli:$TAUTULLI_VERSION
  #   container_name: tautulli
  #   hostname: tautulli
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - tautulli-config:/config
  #   ports:
  #     - "8181:8181"

  jellyfin:
    image: linuxserver/jellyfin:$JELLYFIN_VERSION
    container_name: jellyfin
    hostname: jellyfin
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=jellyfin.$DOMAIN_NAME
    volumes:
      - jellyfin-config:/config
      - $SHARED_FOLDER/Media:/media
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12

volumes:
  # plex-config:
  # tautulli-config:
  jellyfin-config:
