services:
  gitlab:
    image: gitlab/gitlab-ce:$GITLAB_VERSION
    container_name: gitlab
    hostname: gitlab
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = '$GITLAB_ROOT_PASSWORD'
    volumes:
      - config:/etc/gitlab
      - data:/var/opt/gitlab
    ports:
      - 80:80
      - 443:443
      - 22:22
    networks:
      - dev

volumes:
  config:
  data:

networks:
  dev:
    external: true
