services:
  # qbittorrent:
  #   image: linuxserver/qbittorrent:$QBITTORRENT_VERSION
  #   container_name: qbittorrent
  #   hostname: qbittorrent
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #     - WEBUI_PORT=5000
  #   volumes:
  #     - config:/config
  #     - $SHARED_FOLDER/Downloads/Torrents:/downloads
  #   ports:
  #     - "6881:6881"
  #     - "6881:6881/udp"
  #     - "5000:5000"

  qbittorrent-vpn:
    image: markusmcnugen/qbittorrentvpn:latest
    container_name: qbittorrent-vpn
    hostname: qbittorrent-vpn
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - LAN_NETWORK=$LAN_NETWORK_CIDR
      - NAME_SERVERS=$DNS_IPS_COMMA_SEPARATED
      - VPN_ENABLED=yes
      - VPN_USERNAME=$VPN_USERNAME
      - VPN_PASSWORD=$VPN_PASSWORD
    ports:
      - "8080:8080"
      - "8999:8999"
      - "8999:8999/udp"
    volumes:
      - vpn-config:/config
      - $SHARED_FOLDER/Downloads/Torrents:/downloads

volumes:
  # config:
  vpn-config:
