services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:$CLOUDFLARE_DDNS_VERSION
    container_name: cloudflare-ddns-$APPLICATION_NAME_EXPOSED
    restart: unless-stopped
    environment:
      API_KEY: $CLOUDFLARE_DDNS_API_KEY
      ZONE: $CLOUDFLARE_DDNS_DOMAIN
      SUBDOMAIN: $CLOUDFLARE_DDNS_SUBDOMAIN
