services:
  # plex:
  #   image: linuxserver/plex:$PLEX_VERSION
  #   container_name: plex
  #   hostname: plex
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #     - VERSION=docker
  #     - PLEX_CLAIM=$PLEX_CLAIM_TOKEN
  #   volumes:
  #     - plex-config:/config
  #     - $SHARED_FOLDER/Media:/media

  # tautulli:
  #   image: linuxserver/tautulli:$TAUTULLI_VERSION
  #   container_name: tautulli
  #   hostname: tautulli
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - tautulli-config:/config
  #   ports:
  #     - 8181:8181

  jellyfin:
    image: linuxserver/jellyfin:$JELLYFIN_VERSION
    container_name: jellyfin
    hostname: jellyfin
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=jellyfin.$DOMAIN_NAME
    volumes:
      - jellyfin-config:/config
      - $SHARED_FOLDER/Media:/media
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12

  bazarr:
    image: linuxserver/bazarr:$BAZARR_VERSION
    container_name: bazarr
    hostname: bazarr
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
    volumes:
      - bazarr-config:/config
      - $SHARED_FOLDER/Media/Movies:/movies
      - $SHARED_FOLDER/Media/TvShows:/tv
    ports:
      - 6767:6767

  radarr:
    image: linuxserver/radarr:$RADARR_VERSION
    container_name: radarr
    hostname: radarr
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
    volumes:
      - radarr-config:/config
      - $SHARED_FOLDER/Media/Movies:/movies
      - $SHARED_FOLDER/Downloads/Torrents:/downloads
    ports:
      - 7878:7878

  sonarr:
    image: linuxserver/sonarr:$SONARR_VERSION
    container_name: sonarr
    hostname: sonarr
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
    volumes:
      - sonarr-config:/config
      - $SHARED_FOLDER/Media/TvShows:/tv
      - $SHARED_FOLDER/Downloads/Torrents:/downloads
    ports:
      - 8989:8989

  lidarr:
    image: linuxserver/lidarr:$LIDARR_VERSION
    container_name: lidarr
    hostname: lidarr
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
    volumes:
      - lidarr-config:/config
      - $SHARED_FOLDER/Media/Music:/music
      - $SHARED_FOLDER/Downloads/Torrents:/downloads
    ports:
      - 8686:8686

  jackett:
    image: linuxserver/jackett:$JACKETT_VERSION
    container_name: jackett
    hostname: jackett
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
    volumes:
      - jackett-config:/config
      - $SHARED_FOLDER/Downloads/Torrents:/downloads
    ports:
      - 9117:9117

  # qbittorrent:
  #   image: linuxserver/qbittorrent:$QBITTORRENT_VERSION
  #   container_name: qbittorrent
  #   hostname: qbittorrent
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #     - WEBUI_PORT=5000
  #   volumes:
  #     - qbittorrent-config:/config
  #     - $SHARED_FOLDER/Downloads/Torrents:/downloads
  #   ports:
  #     - 6881:6881
  #     - 6881:6881/udp
  #     - 5000:5000

  qbittorrent-vpn:
    image: markusmcnugen/qbittorrentvpn:latest
    container_name: qbittorrent-vpn
    hostname: qbittorrent-vpn
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - LAN_NETWORK=$LAN_NETWORK_CIDR
      - NAME_SERVERS=$DNS_IPS_COMMA_SEPARATED
      - VPN_ENABLED=yes
      - VPN_USERNAME=$VPN_USERNAME
      - VPN_PASSWORD=$VPN_PASSWORD
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - qbittorrent-vpn-config:/config
      - $SHARED_FOLDER/Downloads/Torrents:/downloads

  # sabnzbd:
  #   image: linuxserver/sabnzbd:$SABNZBD_VERSION
  #   container_name: sabnzbd
  #   hostname: sabnzbd
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - sabnzbd-config:/config
  #     - $SHARED_FOLDER/Downloads/Usenet:/downloads
  #     - $SHARED_FOLDER/Downloads/Usenet/Incomplete:/incomplete-downloads
  #   ports:
  #     - 8080:8080
  #     - 9090:9090

  # overseerr:
  #   image: hotio/overseerr:$OVERSEERR_VERSION
  #   container_name: overseerr
  #   hostname: overseerr
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - overseerr-config:/config
  #   ports:
  #     - 5055:5055

  # requestrr:
  #   image: linuxserver/requestrr:$REQUESTRR_VERSION
  #   container_name: requestrr
  #   hostname: requestrr
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - requestrr-config:/config
  #   ports:
  #     - 4545:4545

  # organizr:
  #   image: organizr/organizr:$ORGANIZR_VERSION
  #   container_name: organizr
  #   hostname: organizr
  #   domainname: $DOMAIN_NAME
  #   restart: unless-stopped
  #   environment:
  #     - PUID=$USER_PUID
  #     - PGID=$USER_PGID
  #     - TZ=America/Sao_Paulo
  #     - branch=v2-master
  #     - fpm=true
  #   volumes:
  #     - organizr-config:/config
  #   ports:
  #     - 80:80

volumes:
  plex-config:
  tautulli-config:
  emby-config:
  embystat-config:
  jellyfin-config:
  jackett-config:
  qbittorrent-config:
  qbittorrent-vpn-config:
  sabnzbd-config:
  radarr-config:
  sonarr-config:
  lidarr-config:
  bazarr-config:
  overseerr-config:
  requestrr-config:
  organizr-config:
