services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui-cuda
    hostname: open-webui-cuda
    restart: unless-stopped
    volumes:
      - data:/app/backend/data
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

volumes:
  data:
