services:
  grafana:
    image: grafana/grafana:$GRAFANA_VERSION
    container_name: grafana
    hostname: grafana
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    volumes:
      - config:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  config:
