services:
  bitwarden:
    image: bitwardenrs/server:$BITWARDEN_VERSION
    container_name: bitwarden
    hostname: bitwarden
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    volumes:
      - config:/data
    ports:
      - 80:80

volumes:
  config:
