services:
  uptime-kuma:
    image: louislam/uptime-kuma:$UPTIME_KUMA_VERSION
    container_name: uptime-kuma
    hostname: uptime-kuma
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    volumes:
      - config:/app/data
    ports:
      - 3001:3001

volumes:
  config:
