services:
  transmission-vpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-vpn
    hostname: transmission-vpn
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
      - LOCAL_NETWORK=$LAN_NETWORK_CIDR
      - OPENVPN_PROVIDER=$VPN_PROVIDER
      - OPENVPN_USERNAME=$VPN_USERNAME
      - OPENVPN_PASSWORD=$VPN_PASSWORD
      - OPENVPN_CONFIG=$VPN_SERVERS_COMMA_SEPARATED
    ports:
      - 9091:9091
    volumes:
      - config:/config
      - $SHARED_FOLDER/Downloads/Torrents:/data
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m

volumes:
  config:
