services:
  duplicati:
    image: linuxserver/duplicati:$DUPLICATI_VERSION
    container_name: duplicati
    hostname: duplicati
    domainname: $DOMAIN_NAME
    restart: unless-stopped
    environment:
      - PUID=$USER_PUID
      - PGID=$USER_PGID
      - TZ=America/Sao_Paulo
    volumes:
      - config:/config
      - $SHARED_FOLDER/Backups/Duplicati:/backups
      - $PATH_1_TO_BACKUP:/source1
      - $PATH_2_TO_BACKUP:/source2
    ports:
      - 8200:8200

volumes:
  config:
